name: Unit Tests

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
jobs:
    build:
        runs-on: ${{ matrix.os }}
        strategy:
            fail-fast: false
            matrix:
                os: [ macos-latest, ubuntu-latest, windows-latest ]
        steps:
            -   uses: actions/checkout@v2
            -   name: Set up JDK 15
                uses: actions/setup-java@v2
                with:
                    distribution: 'temurin'
                    java-version: 17
            -   run: choco install bonjour
                if: runner.os == 'Windows'
            -   uses: ilammy/msvc-dev-cmd@v1
                if: runner.os == 'Windows'
            -   uses: microsoft/setup-msbuild@v1.1
                if: runner.os == 'Windows'
                with:
                    msbuild-architecture: x64
            -   name: Cache local Maven repository
                uses: actions/cache@v2
                with:
                    path: ~/.m2/repository
                    key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
                    restore-keys: |
                        ${{ runner.os }}-maven-
            -   name: patch
                uses: actions/setup-python@v2
                with:
                    python-version: '3.x' # Version range or exact version of a Python version to use, using SemVer's version range syntax
                    architecture: 'x64' # optional x64 or x86. Defaults to x64 if not specified
            - run: python patch.py
            -   name: Build with Maven
                run: mvn -ntp verify -DskipITs -DskipSign -B -Drevision=0 -Pinstaller
            - name: release
              uses: "marvinpinto/action-automatic-releases@latest"
              with:
                  repo_token: "${{ secrets.GITHUB_TOKEN }}"
                  automatic_release_tag: "latest"
                  prerelease: true
                  title: "Development Build"
                  files: |
                    LICENSE.txt
                    windows/target/release/*.exe
                    windows/target/release/*.msi
                    osx/target/release/*.zip
                    osx/target/release/*.pkg
                    cli/osx/target/release/*(pkg|tar.gz|exe|msi|deb|rpm)
